#!/usr/bin/python

import sqlite3

conn = sqlite3.connect('employeeshiftsdb.db')
print "Opened database successfully";

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMES BEARD', 'CHEF', 'MONDAY',8,1,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('GORDON RAMSAY', 'CHEF', 'MONDAY',1,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMIE OLIVER', 'CHEF', 'MONDAY',5,10,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMES BEARD', 'CHEF', 'TUESDAY',8,2,'am','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('EMERIL LAGASSE', 'CHEF', 'TUESDAY',2,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('BOBBY FLAY', 'CHEF', 'TUESDAY',5,10,'pm','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('RACHAEL RAY', 'CHEF', 'WEDNESDAY',8,12,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMES BEARD', 'CHEF', 'WEDNESDAY',12,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('THOMAS KELLER', 'CHEF', 'WEDNESDAY',5,10,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('GORDON RAMSAY', 'CHEF', 'THURSDAY',8,12,'am','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMIE OLIVER', 'CHEF', 'THURSDAY',12,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMES BEARD', 'CHEF', 'THURSDAY',5,10,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('RACHAEL RAY', 'CHEF', 'FRIDAY',8,1,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('EMERIL LAGASSE', 'CHEF', 'FRIDAY',1,5,'pm','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('BOBBY FLAY', 'CHEF', 'FRIDAY',5,10,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('THOMAS KELLER', 'CHEF', 'SATURDAY',8,12,'am','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('GORDON RANMSAY', 'CHEF', 'SATURDAY',12,5,'pm','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('EMERIL LAGASSE', 'CHEF', 'SATURDAY',5,10,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMES BEARD', 'CHEF', 'SUNDAY',8,12,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMIE OLIVER', 'CHEF', 'SUNDAY',12,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('RACHAEL RAY', 'CHEF', 'SUNDAY',5,10,'pm','pm')");



conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('THOMAS KELLER', 'CHEF', 'MONDAY',8,1,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('BOBBY FLAY', 'CHEF', 'MONDAY',1,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('EMERIL LAGASSE', 'CHEF', 'MONDAY',5,10,'pm','pm')");


conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMIE OLIVER', 'CHEF', 'TUESDAY',8,2,'am','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('GORDON RAMSAY', 'CHEF', 'TUESDAY',2,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('RACHAEL RAY', 'CHEF', 'TUESDAY',5,10,'pm','pm')");


	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('THOMAS KELLER', 'CHEF', 'WEDNESDAY',8,12,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('BOBBY FLAY', 'CHEF', 'WEDNESDAY',12,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('EMERIL LAGASSE', 'CHEF', 'WEDNESDAY',5,10,'pm','pm')");



conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('RACHAEL RAY', 'CHEF', 'THURSDAY',8,12,'am','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('BOBBY FLAY', 'CHEF', 'THURSDAY',12,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMIE OLIVER', 'CHEF', 'THURSDAY',5,10,'pm','pm')");



conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('GORDON RANMSAY', 'CHEF', 'FRIDAY',8,1,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('THOMAS KELLER', 'CHEF', 'FRIDAY',1,5,'pm','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMES BEARD', 'CHEF', 'FRIDAY',5,10,'pm','pm')");



conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('GORDON RANMSAY', 'CHEF', 'SATURDAY',8,12,'am','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('THOMAS KELLER', 'CHEF', 'SATURDAY',12,5,'pm','pm')");
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JAMIE OLIVER', 'CHEF', 'SATURDAY',5,10,'pm','pm')");



conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('EMERIL LAGASSE', 'CHEF', 'SUNDAY',8,12,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('RACHAEL RAY', 'CHEF', 'SUNDAY',12,5,'pm','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('BOBBY FLAY', 'CHEF', 'SUNDAY',5,10,'pm','pm')");

	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('HOLLY BESKE', 'WAITER', 'MONDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('HOLLY BESKE', 'WAITER', 'TUESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('HOLLY BESKE', 'WAITER', 'WEDNESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('HOLLY BESKE', 'WAITER', 'THURSDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('HOLLY BESKE', 'WAITER', 'FRIDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('HOLLY BESKE', 'WAITER', 'SATURDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('HOLLY BESKE', 'WAITER', 'SUNDAY',8,10,'am','pm')");


conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('TIMOTHY SMITH', 'WAITER', 'MONDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('TIMOTHY SMITH', 'WAITER', 'TUESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('TIMOTHY SMITH', 'WAITER', 'WEDNESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('TIMOTHY SMITH', 'WAITER', 'THURSDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('TIMOTHY SMITH', 'WAITER', 'FRIDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('TIMOTHY SMITH', 'WAITER', 'SATURDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('TIMOTHY SMITH', 'WAITER', 'SUNDAY',8,10,'am','pm')");

	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JIMMY CHU', 'WAITER', 'MONDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JIMMY CHU', 'WAITER', 'TUESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JIMMY CHU', 'WAITER', 'WEDNESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JIMMY CHU', 'WAITER', 'THURSDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JIMMY CHU', 'WAITER', 'FRIDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JIMMY CHU', 'WAITER', 'SATURDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JIMMY CHU', 'WAITER', 'SUNDAY',8,10,'am','pm')");

	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('SALLY SEASHELLS', 'WAITER', 'MONDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('SALLY SEASHELLS', 'WAITER', 'TUESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('SALLY SEASHELLS', 'WAITER', 'WEDNESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('SALLY SEASHELLS', 'WAITER', 'THURSDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('SALLY SEASHELLS', 'WAITER', 'FRIDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('SALLY SEASHELLS', 'WAITER', 'SATURDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('SALLY SEASHELLS', 'WAITER', 'SUNDAY',8,10,'am','pm')");
	  
	  
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('MOIRA STEVENS', 'WAITER', 'MONDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('MOIRA STEVENS', 'WAITER', 'TUESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('MOIRA STEVENS', 'WAITER', 'WEDNESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('MOIRA STEVENS', 'WAITER', 'THURSDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('MOIRA STEVENS', 'WAITER', 'FRIDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('MOIRA STEVENS', 'WAITER', 'SATURDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('MOIRA STEVENS', 'WAITER', 'SUNDAY',8,10,'am','pm')");

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('KEVIN PAUL', 'BUSSER', 'MONDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('KEVIN PAUL', 'BUSSER', 'TUESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('KEVIN PAUL', 'BUSSER', 'WEDNESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('KEVIN PAUL', 'BUSSER', 'THURSDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('KEVIN PAUL', 'BUSSER', 'FRIDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('KEVIN PAUL', 'BUSSER', 'SATURDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('KEVIN PAUL', 'BUSSER', 'SUNDAY',8,10,'am','pm')");
	  

conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JEAN ELLERBY', 'BUSSER', 'MONDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JEAN ELLERBY', 'BUSSER', 'TUESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JEAN ELLERBY', 'BUSSER', 'WEDNESDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JEAN ELLERBY', 'BUSSER', 'THURSDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JEAN ELLERBY', 'BUSSER', 'FRIDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JEAN ELLERBY', 'BUSSER', 'SATURDAY',8,10,'am','pm')");
conn.execute("INSERT INTO EMPLOYEESHIFTS (NAME,ROLE,DAY,SHIFTSTART,SHIFTEND,STARTPERIOD,ENDPERIOD) \
      VALUES ('JEAN ELLERBY', 'BUSSER', 'SUNDAY',8,10,'am','pm')");

	  
conn.commit()
print "Records created successfully";
conn.close()