///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The New_Recording recording.
    /// </summary>
    [TestModule("e0fddb67-b0c1-45fa-85cc-ed9bc48c2b5f", ModuleType.Recording, 1)]
    public partial class New_Recording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the New_Repository repository.
        /// </summary>
        public static New_Repository repo = New_Repository.Instance;

        static New_Recording instance = new New_Recording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public New_Recording()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static New_Recording Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'file:///C:/Users/hagar/Desktop/html%20pages/home.html' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("file:///C:/Users/hagar/Desktop/html%20pages/home.html", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 146;258.", repo.HomeHtml.SelfInfo, new RecordItemIndex(1));
            repo.HomeHtml.Self.Click("146;258");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 197;257.", repo.HomeHtml.SelfInfo, new RecordItemIndex(2));
            repo.HomeHtml.Self.Click("197;257");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 174;54.", repo.HomeHtml.SelfInfo, new RecordItemIndex(5));
            repo.HomeHtml.Self.Click("174;54");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 293;428.", repo.HomeHtml.SelfInfo, new RecordItemIndex(6));
            repo.HomeHtml.Self.Click("293;428");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 812;338.", repo.HomeHtml.SelfInfo, new RecordItemIndex(7));
            repo.HomeHtml.Self.Click("812;338");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(8));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 1451;828.", repo.HomeHtml.SelfInfo, new RecordItemIndex(9));
            repo.HomeHtml.Self.Click("1451;828");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 183;50.", repo.HomeHtml.SelfInfo, new RecordItemIndex(11));
            repo.HomeHtml.Self.Click("183;50");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 311;610.", repo.HomeHtml.SelfInfo, new RecordItemIndex(12));
            repo.HomeHtml.Self.Click("311;610");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 798;614.", repo.HomeHtml.SelfInfo, new RecordItemIndex(13));
            repo.HomeHtml.Self.Click("798;614");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 1493;881.", repo.HomeHtml.SelfInfo, new RecordItemIndex(15));
            repo.HomeHtml.Self.Click("1493;881");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(16));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 135;44.", repo.HomeHtml.SelfInfo, new RecordItemIndex(17));
            repo.HomeHtml.Self.Click("135;44");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 249;734.", repo.HomeHtml.SelfInfo, new RecordItemIndex(18));
            repo.HomeHtml.Self.Click("249;734");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 185;53.", repo.HomeHtml.SelfInfo, new RecordItemIndex(19));
            repo.HomeHtml.Self.Click("185;53");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(20));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 85;617.", repo.HomeHtml.SelfInfo, new RecordItemIndex(21));
            repo.HomeHtml.Self.Click("85;617");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 144;59.", repo.HomeHtml.SelfInfo, new RecordItemIndex(22));
            repo.HomeHtml.Self.Click("144;59");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(23));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 154;726.", repo.HomeHtml.SelfInfo, new RecordItemIndex(24));
            repo.HomeHtml.Self.Click("154;726");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(25));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 156;35.", repo.HomeHtml.SelfInfo, new RecordItemIndex(26));
            repo.HomeHtml.Self.Click("156;35");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 254;13.", repo.HomeHtml.SelfInfo, new RecordItemIndex(27));
            repo.HomeHtml.Self.Click("254;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 132;311.", repo.HomeHtml.SelfInfo, new RecordItemIndex(28));
            repo.HomeHtml.Self.Click("132;311");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 115;265.", repo.HomeHtml.SelfInfo, new RecordItemIndex(29));
            repo.HomeHtml.Self.Click("115;265");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 211;55.", repo.HomeHtml.SelfInfo, new RecordItemIndex(30));
            repo.HomeHtml.Self.Click("211;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'HomeHtml' at 211;55.", repo.HomeHtml.SelfInfo, new RecordItemIndex(31));
            repo.HomeHtml.Self.MoveTo("211;55");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'HomeHtml' at 238;29.", repo.HomeHtml.SelfInfo, new RecordItemIndex(32));
            repo.HomeHtml.Self.MoveTo("238;29");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'HomeHtml' at 238;29.", repo.HomeHtml.SelfInfo, new RecordItemIndex(33));
            repo.HomeHtml.Self.MoveTo("238;29");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'HomeHtml' at 271;11.", repo.HomeHtml.SelfInfo, new RecordItemIndex(34));
            repo.HomeHtml.Self.MoveTo("271;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 128;422.", repo.HomeHtml.SelfInfo, new RecordItemIndex(35));
            repo.HomeHtml.Self.Click("128;422");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 253;37.", repo.HomeHtml.SelfInfo, new RecordItemIndex(36));
            repo.HomeHtml.Self.Click("253;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 451;70.", repo.HomeHtml.SelfInfo, new RecordItemIndex(37));
            repo.HomeHtml.Self.Click("451;70");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 378;60.", repo.HomeHtml.SelfInfo, new RecordItemIndex(38));
            repo.HomeHtml.Self.Click("378;60");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 597;57.", repo.HomeHtml.SelfInfo, new RecordItemIndex(39));
            repo.HomeHtml.Self.Click("597;57");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeHtml' at 380;275.", repo.HomeHtml.SelfInfo, new RecordItemIndex(40));
            repo.HomeHtml.Self.Click("380;275");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
